### ISSUE TITLE
How about some charts?

### ISSUE THREAD

**Issue by disaster123** [olaviinha/PEPM#2]
Looks great thanks for your work.how about real-time stock charts?

**Comment by o-inha** [comment]
Thanks for the idea! I've indeed been thinking about it. I think the Bloomberg API has the necessary data, and it wouldn't even increase the number of API calls, since it would replace the "3 day history" call. On the other hand, the point of this web app is to provide an overview of the current situation of the portfolio with nothing extra, and charts seem a bit of "extra" to me. It would perhaps require a second view for charts, to prevent a mess. I will think about it some more, thanks again!

**Comment by o-inha** [comment]
Alright, you can now toggle some mini charts in the last column.

a) Price changed since purchase date.
b) Price changed in the last 3 days.

Horizontal line is the price you paid.

![Imaginary portfolio viewed on FINNSTONKS PEPM](https://storage.googleapis.com/olaviinha/github/pepm/charts1.gif)

As a minus, FinnStonks now consumes 3 API calls per pageload (perviously 2). This means with the RapidAPI Freemium plan, you can load the page about 5 times a day.
